Update Dependencies & Change Some Paths in Pubspec.yaml
kevinsullivan/concepts_exploration pull request #7
Opened 2023-06-21 00:48 UTC by RoboticMind

* Update some of the dependency versions to work with Flutter `v3.10.5`
* Change paths in the pubspec.yaml from `/opt/devel/uva/repos/*` to `/workspaces/*` to match the container

2023-06-21 00:59 UTC, nicholasphair requested changes
Thanks for this. Once there is an updated docker image to test on I can try it out and merge.

2023-06-21 00:59 UTC, nicholasphair commented on sequentialcompose/impl/frontend/linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux
> +/root/.pub-cache/hosted/pub.dev/url_launcher_linux-3.0.5/
I don't think we want to support linux desktop apps. So any `frontend/linux` directories should be removed.

2023-06-21 01:40 UTC, RoboticMind commented on sequentialcompose/impl/frontend/linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux
> +/root/.pub-cache/hosted/pub.dev/url_launcher_linux-3.0.5/
Whoops, forgot that I had accidentally added the Linux Desktop platform at one point. I think I got all the relevant files/folders deleted now

2023-06-21 15:11 UTC, RoboticMind commented
Now made a PR for updating the docker build https://github.com/kevinsullivan/moralpain_config/pull/15

Also a bit clunky, but you can automate the process of fixing up the packages folder by running this command that finds all package folders and cleans and reinstalls the depends 

```bash
find . -name "packages" -execdir sh -c "cd packages && flutter clean && flutter pub get" \;
```

2023-06-21 19:17 UTC, RoboticMind commented
Hmm something strange I just noticed. Each app separately runs without issue but running the sequential compose generates this runtime error once things are started:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following ProviderNotFoundException was thrown building ThermometerLabel<ThermometerCubit>:
Error: Could not find the correct Provider<ThermometerCubit> above this
BlocBuilder<ThermometerCubit, double> Widget
```

Here's how it shows on the page itself:
![image](https://github.com/kevinsullivan/concepts_exploration/assets/30132912/00394d5e-b4d0-49f5-9cf0-921d6099191d)

2023-06-23 04:47 UTC, nicholasphair commented
As I think more about this, I think the right path for now is to use relative paths. Could we separate this into two prs. One for the version upgrades and the other for that paths?

2023-06-23 15:15 UTC, RoboticMind commented
Removed the path changes from this PR now, will create another for relative PRs in a bit

2023-06-23 18:35 UTC, merged